packages:
  - .

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
    - arm64

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi

allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
