import type { LayoutCollection } from "./types";

export const navigationCollections: LayoutCollection[] = [
	{
		key: "mainNavigation",
		label: "MAIN ROOM NAVIGATION",
		room: "main",
		position: { x: 0, y: 0, z: 0 },
		objects: [
			{
				key: "menu",
				label: "MENU BOARD",
				zone: {
					position: { x: 0, z: -7.5 },
					radius: 4.4,
					label: "VIEW MENU",
					emoji: "🍔",
				},
				glow: { position: { x: 0, z: -7.5 }, color: 0xe8a946 },
				hangingSign: {
					position: { x: 0, z: -3.2 },
					ry: 0,
					text: "MENU",
					arrow: "▼",
					color: 0xe8a946,
				},
			},
			{
				key: "about",
				label: "ABOUT WALL",
				zone: {
					position: { x: -12.2, z: -2.0 },
					radius: 1.8,
					label: "ABOUT GREASYMAC",
					emoji: "🎮",
				},
				glow: { position: { x: -12.2, z: -2.0 }, color: 0xff2255 },
				hangingSign: {
					position: { x: -5.0, z: -1.8 },
					ry: Math.PI * 0.1,
					text: "ABOUT",
					arrow: "◄",
					color: 0xcc2828,
				},
			},
			{
				key: "loreRoom",
				label: "LORE HALL DOOR",
				door: {
					position: { x: -13.78, y: 1.32, z: 2.0 },
					ry: Math.PI / 2,
					title: "LORE HALL",
					subtitle: "deep grease archive",
					accent: 0xfa4040,
				},
				zone: {
					position: { x: -12.8, z: 2.0 },
					radius: 2.2,
					label: "ENTER LORE HALL",
					emoji: "★",
					room: "main",
				},
				glow: { position: { x: -12.6, z: 2.0 }, color: 0xfa4040 },
			},
			{
				key: "fishRoom",
				label: "FISH FREEZER DOOR",
				door: {
					position: { x: 13.78, y: 1.32, z: 6.65 },
					ry: -Math.PI / 2,
					title: "FISH FREEZER",
					subtitle: "what's this?",
					accent: 0x89d8c8,
				},
				zone: {
					position: { x: 12.8, z: 6.65 },
					radius: 2.0,
					label: "ENTER FISH FREEZER",
					emoji: "◆",
					room: "main",
				},
				glow: { position: { x: 12.6, z: 6.65 }, color: 0x89d8c8 },
			},
			{
				key: "liveRoom",
				label: "LIVE ROOM DOOR",
				door: {
					position: { x: 13.78, y: 1.32, z: 1.15 },
					ry: -Math.PI / 2,
					title: "LIVE ROOM",
					subtitle: "screens stay on",
					accent: 0x22aaff,
				},
				zone: {
					position: { x: 12.8, z: 1.15 },
					radius: 2.0,
					label: "ENTER LIVE ROOM",
					emoji: "●",
					room: "main",
				},
				glow: { position: { x: 12.6, z: 1.15 }, color: 0x22aaff },
			},
			{
				key: "kitchenRoom",
				label: "KITCHEN DOOR",
				door: {
					position: { x: -3.65, y: 1.32, z: -11.28 },
					ry: 0,
					title: "KITCHEN",
					subtitle: "employees only-ish",
					accent: 0xe8a946,
				},
				zone: {
					position: { x: -3.65, z: -10.55 },
					radius: 1.9,
					label: "ENTER KITCHEN",
					emoji: "▣",
					room: "main",
				},
				glow: { position: { x: -3.65, z: -10.55 }, color: 0xe8a946 },
			},
		],
	},
	{
		key: "roomExits",
		label: "ROOM EXIT DOORS",
		position: { x: 0, y: 0, z: 0 },
		objects: [
			{
				key: "loreExit",
				label: "LORE HALL EXIT",
				door: {
					position: { x: -16.72, y: 1.32, z: 2.0 },
					ry: -Math.PI / 2,
					title: "DINER",
					subtitle: "return",
					accent: 0xe8a946,
				},
				zone: {
					key: "exitMain",
					position: { x: -16.6, z: 2.0 },
					radius: 2.1,
					label: "BACK TO DINER",
					emoji: "↩",
					room: "lore",
				},
			},
			{
				key: "fishExit",
				label: "FISH FREEZER EXIT",
				door: {
					position: { x: 16.72, y: 1.32, z: 6.65 },
					ry: Math.PI / 2,
					title: "DINER",
					subtitle: "return",
					accent: 0xe8a946,
				},
				zone: {
					key: "exitMain",
					position: { x: 16.85, z: 6.65 },
					radius: 2.1,
					label: "BACK TO DINER",
					emoji: "↩",
					room: "fish",
				},
			},
			{
				key: "liveExit",
				label: "LIVE ROOM EXIT",
				door: {
					position: { x: 16.72, y: 1.32, z: -5.4 },
					ry: Math.PI / 2,
					title: "DINER",
					subtitle: "return",
					accent: 0xe8a946,
				},
				zone: {
					key: "exitMain",
					position: { x: 16.85, z: -5.4 },
					radius: 2.1,
					label: "BACK TO DINER",
					emoji: "↩",
					room: "live",
				},
			},
			{
				key: "kitchenExit",
				label: "KITCHEN EXIT",
				door: {
					position: { x: -3.65, y: 1.32, z: -14.92 },
					ry: Math.PI,
					title: "DINER",
					subtitle: "return",
					accent: 0xe8a946,
				},
				zone: {
					key: "exitMain",
					position: { x: -3.65, z: -14.95 },
					radius: 2.1,
					label: "BACK TO DINER",
					emoji: "↩",
					room: "kitchen",
				},
			},
		],
	},
];
