name: CI
on: [push, pull_request]

jobs:
  test:
    name: Install dependencies and build
    runs-on: ubuntu-latest
    steps:
    
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
